fix error when cannot access /proc/loadavg
liquidprompt/liquidprompt pull request #587
Opened 2019-10-10 15:31 UTC by go2null

encountered this error on Termux
```
bash: /proc/loadavg: Permission denied
```

2019-10-10 15:52 UTC, Rycieos commented
I don't think this is a good idea.

If there is an issue reading from `/proc/loadavg`, the user needs to know so that they can fix that. Suppressing the error message will make it much harder to debug.

What even happens if the lookup is skipped? The variable will not have any value in it, which might cause an error somewhere else.

I'd much rather say that users must be able to read from `/proc/loadavg`, since that's pretty standard. Why can't you read it? What reasons might system admins disable that?

2019-11-25 16:16 UTC, go2null commented
I changed it to only skip if in Termux.

This issue arises in Termux (linux shell on Android) which doesn't support `/proc`
- https://wiki.termux.com/wiki/Differences_from_Linux
- https://github.com/termux/termux-app/issues/299

2019-11-25 16:24 UTC, Rycieos commented
Thanks for the links.

From the issue thread:
> They are effectively abandoning practical Linux compatibility.

I agree. Yikes. IMO, this means, from a shell perspective, Android is no longer Linux.

I don't like where you added this extra check, since it will be run every time for all Linux boxes. We are trying to remove total running code, not add more.

For those two reasons, I see an argument for adding a new OS type, Android. It would add a slight amount of extra startup time, but then we could support all these divergences from normal Linux.

2019-11-25 17:59 UTC, go2null commented
> I don't like where you added this extra check, since it will be run every time for all Linux boxes. We are trying to remove total running code, not add more.

I've changed 
- to a more elegant solution - use `uptime` if available, otherwise revert to original behaviour
- created appropriate function definition to avoid checking everytime

2019-11-25 18:04 UTC, Rycieos commented
Better, but now you have a situation where if both `/prod/loadavg` is not readable and `uptime` doesn't exist, then `_lp_cpu_load()` won't be defined, which won't be a helpful error message for any user that runs into that.

2019-11-25 18:45 UTC, go2null commented
not really, the `uptime` function is only defined BOTH conditions are true, otherwise it uses the normal `/proc/loadavg` parsing.

2019-11-25 18:51 UTC, Rycieos commented
Hm, true. I blame Monday.

Seems like an OK workaround then.

2020-08-26 08:01 UTC, adamryczkowski commented
I hope this will get pushed mainstream, so I don't have to patch the code manually on each Android device.

2020-09-07 18:02 UTC, Rycieos requested changes
Sorry for the delay, I was on a much needed vacation this past week.

Yikes, it's already been almost a year since this was opened? Lucky for you I guess, since I hate this much less than I did back then.

I'm mostly fine with this, I just need a few simple things (plus the specific suggestion):
1. Rebase to fix the conflicts.
2. Paste me the output of `LC_ALL=C uptime` on your Android machine, so I can verify that it will parse similar to other `uptime` outputs.

As a bonus (otherwise as a note to myself for the future), this should be optimized somehow so as to not duplicate the definition in the `SunOS` section, since it's the same.

2020-09-07 18:02 UTC, Rycieos commented on liquidprompt
> +                lp_cpu_load="$(uptime | sed 's/.*load average: \([0-9.]*\).*/\1/')"
```suggestion
                lp_cpu_load="$(LC_ALL=C uptime | sed 's/.*load average: \([0-9.]*\).*/\1/')"
```

2023-10-23 20:27 UTC, closed without merging

2023-10-23 20:27 UTC, Rycieos commented
I pulled, rebased, and fixed conflicts to merge this. GitHub won't show it as merged, since the changes won't come from your personal branch.