Add LP_THEME variable for controlling current theme
liquidprompt/liquidprompt pull request #792
Opened 2023-10-14 21:38 UTC by Rycieos

LP_THEME is always set to the currently active theme when changed by lp_theme(). It can also be assigned a theme name to have lp_theme() called automatically. This is useful for interacting with tools like direnv that cannot call shell functions since they exist in a subshell.

Closes #721

2023-10-15 09:21 UTC, nojhan requested changes
Awesome, works like a charm with direnv!

Shouldn't we have tests for checking if `LP_THEME` is correctly set after calling `lp_theme`, and conversely?

2023-10-15 09:21 UTC, nojhan commented on docs/functions/public.rst
> +   like calling this function. :envvar:`LP_THEME` will always hold the
The first sentence is a bit hard to grasp. What about: "The variable LP_THEME can be set to a theme name, which is essentially equivalent to calling this function."

2023-10-15 15:30 UTC, Rycieos commented
Good call on tests. I added some, and reworded the docs with your suggestion.

2023-10-16 19:46 UTC, merged

2023-10-16 19:47 UTC, Rycieos commented
> I added an FAQ item to recall that: [How to change the configuration depending on the directory?](https://github.com/liquidprompt/liquidprompt/wiki/FAQ#how-to-change-the-configuration-depending-on-the-directory).

You probably don't need `export` in that line, since Liquid Prompt runs in the shell.

2023-10-18 06:19 UTC, nojhan commented
Actually, it does not work without `export`. The [direnv man](https://direnv.net/man/direnv.1.html) states that "all exported variables are then captured by direnv and then made available to your current shell".