Add extra options to theme-preview.sh for config
liquidprompt/liquidprompt pull request #805
Opened 2023-11-11 19:52 UTC by Rycieos

The original intent for theme-preview.sh was to have a reference for a static output of a theme. So all runs of the tool for a specific theme would always show the same output.

But a different, completely valid use is to see how a theme would look with your config, or to see how changing your config might change how a theme looks.

Add optional arguments that will allow for loading the user config, input files, or to return to the original functionality of locking the `COLUMNS` to a set value.

There is still no way to control the mocked data, and there might still be some weird quirks with the imbedded config in the tool conflicting with user config.

Fix the minimal theme using the wrong `PS1` variable.
Fix Zsh crash in unfold theme.

Fixes #800

2023-11-12 15:10 UTC, nojhan requested changes
Awesome, that's going to be useful.

I tested with several themes and presets and it works well, except for the `minimal` theme, which ends on missing LP_PS1_PREFIX.

2023-11-12 15:10 UTC, nojhan commented on tools/theme-preview.sh
> +  -h, --help               Print this help text.
I would sort the options in the reverse order, which is going from the simplest to the more complex: first the _help_, then _reproducible_, then _user-config_, then _config-file_.

2023-11-12 15:10 UTC, nojhan commented on tools/theme-preview.sh
> +Example usage: %s unfold themes/unfold/unfold.theme
I think we need at least an example with _reproducible_, and one with config files, to show how to load presets.

2023-11-12 15:10 UTC, nojhan commented on tools/theme-preview.sh
> +Example usage: %s unfold themes/unfold/unfold.theme
```suggestion
Example usage:
%s alternate_vcs themes/alternate_vcs/alternate_vcs.theme
%s unfold themes/unfold/unfold.theme --reproducible
%s unfold themes/unfold/unfold.theme --user-config --config-file contrib/presets/colors/256-colors-dark.conf
%s 
```

2023-11-12 15:11 UTC, nojhan commented on tools/theme-preview.sh
> +  -h, --help               Print this help text.
And maybe indicate here that presets are config files?

2023-11-12 15:48 UTC, Rycieos commented
> it works well, except for the `minimal` theme, which ends on missing LP_PS1_PREFIX.

So the `minimal` theme is actually not a theme, but instead a "[default theme template](https://liquidprompt.readthedocs.io/en/stable/theme/default.html#templates)" (aka a Liquid Prompt v1 theme). To use such a template, you need to set [LP_PS1_FILE](https://liquidprompt.readthedocs.io/en/stable/theme/default.html#LP_PS1_FILE) to its path.

Likely it should not have been under `themes/`, since that is just confusing. Maybe we move it to a `templates/` directory?

It does leave the UX lacking though. You can load a template like this with an inline config file:
```bash
./tools/theme-preview.sh default --config-file <(echo LP_PS1_FILE=themes/minimal/minimal.ps1)
```
But maybe we add an argument, `--template-file`, that will do that substitution for you?

2023-11-12 17:47 UTC, nojhan commented
> But maybe we add an argument, `--template-file`, that will do that substitution for you?

I guess that would be the clearest option for a naive user, indeed.

2023-11-12 22:26 UTC, Rycieos commented
This is ready for review. The failed docs lint is because I moved the `minimal.ps1` file, and the docs are looking for the new location on the `master` branch.

2023-11-14 07:04 UTC, nojhan approved these changes
Looks good, just two minor (and optional) questions.

2023-11-14 07:04 UTC, nojhan commented on tools/theme-preview.sh
> +                             config file.
This is nitpicking, but I would add "[…] config file (e.g. presets)." to be crystal clear.

2023-11-14 07:04 UTC, nojhan commented on tools/theme-preview.sh
> +}
Shouldn't usage messages be output on stderr? I am always hesitating about that.

2023-11-16 09:04 UTC, nojhan approved these changes

2023-11-18 18:28 UTC, merged